on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${NAME}!!!"
        env:
          NAME: ${{ secrets.MY_REPO_SECRET }}
