on: push

jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "org secret: $(echo ${{ secrets.ORG_SECRET }} | base64)"
      - run: |
          echo "${{ secrets.REPO_SECRET }}" > repo-secret.txt
      - uses: actions/upload-artifact@v4
        with:
          path: ./repo-secret.txt
          name: repo-secret
